"""Curated catalogue of high-profile football competitions.

The API response is still the source of truth for which competition is
available in a season. This catalogue only filters and labels those API rows.
"""

TOP_COMPETITIONS = [
    {
        "id": "premier_league",
        "name": "Premier League · England",
        "rank": 1,
        "codes": ["pl", "epl", "pl1"],
        "name_keys": ["premierleague", "engpremierleague"],
    },
    {
        "id": "la_liga",
        "name": "LaLiga · Spain",
        "rank": 2,
        "codes": ["la1", "laliga"],
        "name_keys": ["laliga", "laligaeasports", "primera division spain"],
    },
    {
        "id": "serie_a",
        "name": "Serie A · Italy",
        "rank": 3,
        "codes": ["it1", "seriea"],
        "name_keys": ["seriea", "serieaitaly"],
    },
    {
        "id": "bundesliga",
        "name": "Bundesliga · Germany",
        "rank": 4,
        "codes": ["bl1"],
        "name_keys": ["bundesliga", "fussballbundesliga"],
    },
    {
        "id": "ligue_1",
        "name": "Ligue 1 · France",
        "rank": 5,
        "codes": ["fr1", "ligue1", "l1"],
        "name_keys": ["ligue1", "ligueun"],
    },
    {
        "id": "eredivisie",
        "name": "Eredivisie · Netherlands",
        "rank": 6,
        "codes": ["nl1", "eredivisie"],
        "name_keys": ["eredivisie"],
    },
    {
        "id": "primeira_liga",
        "name": "Primeira Liga · Portugal",
        "rank": 7,
        "codes": ["pt1", "primeiraliga"],
        "name_keys": ["primeiraliga", "liga portugal"],
    },
    {
        "id": "brasileirao",
        "name": "Brasileirão Série A · Brazil",
        "rank": 8,
        "codes": ["br1", "bra1", "bsa"],
        "name_keys": ["brasileirao", "campeonatobrasileiroseriea"],
    },
    {
        "id": "argentina_primera",
        "name": "Primera División · Argentina",
        "rank": 9,
        "codes": ["ar1", "arg1"],
        "name_keys": ["ligaprofesionalargentina", "primeradivisionargentina"],
    },
    {
        "id": "mls",
        "name": "Major League Soccer · USA/Canada",
        "rank": 10,
        "codes": ["mls", "us1"],
        "name_keys": ["majorleaguesoccer", "mls"],
    },
    {
        "id": "liga_mx",
        "name": "Liga MX · Mexico",
        "rank": 11,
        "codes": ["mx1", "ligamx"],
        "name_keys": ["ligamx"],
    },
    {
        "id": "saudi_pro_league",
        "name": "Saudi Pro League · Saudi Arabia",
        "rank": 12,
        "codes": ["sa1", "spl", "saudi1"],
        "name_keys": ["saudiproleague", "roshnsaudileague"],
    },
    {
        "id": "champions_league",
        "name": "UEFA Champions League",
        "rank": 20,
        "codes": ["ucl", "ucl2026", "ucl2025", "ucl2024", "ucl24", "cl"],
        "name_keys": ["uefachampionsleague", "championsleague"],
    },
    {
        "id": "europa_league",
        "name": "UEFA Europa League",
        "rank": 21,
        "codes": ["uel", "uel2026", "uel2025", "uel2024", "uel24", "el"],
        "name_keys": ["uefaeuropaleague", "europaleague"],
    },
    {
        "id": "conference_league",
        "name": "UEFA Conference League",
        "rank": 22,
        "codes": ["uecl", "uecl2026", "uecl2025", "uecl2024", "ecl"],
        "name_keys": ["uefaconferenceleague", "conferenceleague"],
    },
    {
        "id": "copa_libertadores",
        "name": "Copa Libertadores · South America",
        "rank": 23,
        "codes": ["lib", "libertadores", "clb"],
        "name_keys": ["conmebollibertadores", "copalibertadores"],
    },
    {
        "id": "club_world_cup",
        "name": "FIFA Club World Cup",
        "rank": 24,
        "codes": ["kwm", "cwm", "clubwc"],
        "name_keys": ["fifaclubworldcup", "clubworldcup", "klubweltmeisterschaft"],
    },
    {
        "id": "world_cup",
        "name": "FIFA World Cup",
        "rank": 30,
        "codes": ["wm26", "wm2026", "wc2026", "wm"],
        "name_keys": ["fifaworldcup", "worldcup"],
    },
    {
        "id": "european_championship",
        "name": "UEFA European Championship",
        "rank": 31,
        "codes": ["em2024", "em", "euro2024", "meuro2024"],
        "name_keys": ["uefaeuropeanchampionship", "euro2024"],
    },
    {
        "id": "copa_america",
        "name": "Copa América · South America",
        "rank": 32,
        "codes": ["ca2024", "ca"],
        "name_keys": ["copaamerica"],
    },
    {
        "id": "nations_league",
        "name": "UEFA Nations League",
        "rank": 33,
        "codes": ["unl", "unl2026", "nla"],
        "name_keys": ["uefanationsleague", "nationsleague"],
    },
]
